name: Build Windows Executable

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # Adjust as needed for your project's Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build executable with PyInstaller
      run: pyinstaller --onefile --noconsole gui.py
    - name: Upload Executable as Artifact
      uses: actions/upload-artifact@v2
      with:
        name: windows-executable
        path: ./dist/*.exe
